// Phase 3: op unit tests vs NumPy reference values.
// Expected outputs generated by scripts/make_ops_reference.py — keep in sync.

#include <cmath>
#include <vector>

#include <gtest/gtest.h>

#include "tinyinfer/ops.h"

namespace {

constexpr float kTol = 1e-5f;

void ExpectNear(const float* got, const float* want, int n) {
    for (int i = 0; i < n; ++i) EXPECT_NEAR(got[i], want[i], kTol) << "index " << i;
}

TEST(Ops, Matvec) {
    // W (3x4 row-major) @ x ; expected = W @ x from NumPy
    const float W[] = {1, 2, 3, 4, 0.5f, -1, 2, 0, 1, 1, 1, 1};
    const float x[] = {1, 2, -1, 0.5f};
    const float kWant[] = {4, -3.5f, 2.5f};
    float out[3] = {};
    tinyinfer::matvec(W, x, out, 3, 4);
    ExpectNear(out, kWant, 3);
}

TEST(Ops, MatvecIdentity) {
    const float W[] = {1, 0, 0, 1};
    const float x[] = {3.25f, -1.5f};
    float out[2] = {};
    tinyinfer::matvec(W, x, out, 2, 2);
    ExpectNear(out, x, 2);
}

TEST(Ops, Rmsnorm) {
    const float x[] = {1.0f, -2.0f, 3.0f, -4.0f};
    const float w[] = {0.5f, 1.0f, 1.5f, 2.0f};
    const float kWant[] = {0.182574174f, -0.730296695f, 1.64316756f, -2.92118678f};
    float out[4] = {};
    tinyinfer::rmsnorm(x, w, out, 4, 1e-6f);
    ExpectNear(out, kWant, 4);
}

TEST(Ops, RmsnormUnitWeight) {
    // With unit weights, output has RMS == 1.
    const float x[] = {2.0f, -1.0f, 0.5f};
    const float w[] = {1.0f, 1.0f, 1.0f};
    float out[3] = {};
    tinyinfer::rmsnorm(x, w, out, 3, 1e-6f);
    float ss = 0;
    for (float v : out) ss += v * v;
    EXPECT_NEAR(std::sqrt(ss / 3), 1.0f, kTol);
}

TEST(Ops, SoftmaxStable) {
    // Large inputs: naive exp would overflow; stable version must not.
    float x[] = {1001.0f, 1002.0f, 1003.0f, 1004.0f};
    const float kWant[] = {0.0320586033f, 0.0871443187f, 0.236882818f, 0.64391426f};
    tinyinfer::softmax(x, 4);
    ExpectNear(x, kWant, 4);
    float s = 0;
    for (float v : x) s += v;
    EXPECT_NEAR(s, 1.0f, kTol);
}

TEST(Ops, Rope) {
    // NeoX style, num_heads=2, head_dim=4, pos=3, theta=10000.
    float q[] = {1, 2, 3, 4, 0.5f, -0.5f, 1.5f, -1.5f};
    float k[] = {2, 0, -1, 3, 1, 1, 1, 1};
    const float kWantQ[] = {-1.41335252f, 1.87911807f, -2.82885748f, 4.05819114f,
                            -0.70667626f, -0.454781767f, -1.41442874f, -1.5143228f};
    const float kWantK[] = {-1.83886499f, -0.0899865006f, 1.27223251f, 2.9986501f,
                            -1.1311125f, 0.969554534f, -0.848872489f, 1.02954553f};
    tinyinfer::rope(q, k, 2, 2, 4, 3);
    ExpectNear(q, kWantQ, 8);
    ExpectNear(k, kWantK, 8);
}

TEST(Ops, RopeGqa) {
    // n_q_heads=4, n_kv_heads=2: k must be indexed by kv-head, not q-head.
    // (Regression test: the old signature corrupted the heap here.)
    float q[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
    float k[] = {2, 0, -1, 3, 1, 1, 1, 1};
    const float kWantQ[] = {-1.41335252f, 1.87911807f, -2.82885748f, 4.05819114f,
                            -5.93780254f, 5.7573362f, -6.22434744f, 8.17637327f,
                            -10.4622526f, 9.63555434f, -9.61983739f, 12.2945554f,
                            -14.9867026f, 13.5137725f, -13.0153273f, 16.4127375f};
    const float kWantK[] = {-1.83886499f, -0.0899865006f, 1.27223251f, 2.9986501f,
                            -1.1311125f, 0.969554534f, -0.848872489f, 1.02954553f};
    tinyinfer::rope(q, k, 4, 2, 4, 3);
    ExpectNear(q, kWantQ, 16);
    ExpectNear(k, kWantK, 8);
}

TEST(Ops, RopePreservesNorm) {
    // Rotation must preserve vector norm.
    float q[] = {1, -2, 3, -4, 0.5f, 0.25f, -0.75f, 1.25f};
    float k[] = {0, 0, 0, 0, 0, 0, 0, 0};
    float before = 0;
    for (float v : q) before += v * v;
    tinyinfer::rope(q, k, 2, 2, 4, 7);
    float after = 0;
    for (float v : q) after += v * v;
    EXPECT_NEAR(before, after, 1e-4f);
}

TEST(Ops, Silu) {
    const float x[] = {-2.0f, -0.5f, 0.0f, 0.5f, 2.0f};
    const float kWant[] = {-0.238405844f, -0.188770334f, 0, 0.311229666f, 1.76159416f};
    for (int i = 0; i < 5; ++i) EXPECT_NEAR(tinyinfer::silu(x[i]), kWant[i], kTol) << "i=" << i;
    float v[] = {-2.0f, -0.5f, 0.0f, 0.5f, 2.0f};
    tinyinfer::vec_silu(v, 5);
    ExpectNear(v, kWant, 5);
}

TEST(Ops, VecMul) {
    const float a[] = {1.5f, -2.0f, 0.0f, 3.25f};
    const float b[] = {2.0f, 0.5f, -1.0f, 4.0f};
    const float kWant[] = {3, -1, 0, 13};
    float out[4] = {};
    tinyinfer::vec_mul(a, b, out, 4);
    ExpectNear(out, kWant, 4);
}

} // namespace
