// Phase 2: safetensors loader tests.
// Fixture generated by scripts/make_test_weights.py — values must match.

#include <cmath>
#include <string>

#include <gtest/gtest.h>

#include "tinyinfer/loader.h"

namespace {

const std::string kFixture = std::string(TEST_DATA_DIR) + "/tiny.safetensors";

TEST(Loader, OpensAndListsTensors) {
    tinyinfer::SafetensorsLoader loader;
    loader.open(kFixture);
    EXPECT_TRUE(loader.is_open());
    EXPECT_EQ(loader.num_tensors(), 4u);
    EXPECT_TRUE(loader.has("weight"));
    EXPECT_TRUE(loader.has("bias"));
    EXPECT_TRUE(loader.has("scalar"));
    EXPECT_TRUE(loader.has("ids"));
    EXPECT_FALSE(loader.has("nope"));
    EXPECT_EQ(loader.metadata().at("format"), "tinyinfer-test");
}

TEST(Loader, WeightValuesMatchPython) {
    tinyinfer::SafetensorsLoader loader;
    loader.open(kFixture);
    const auto& w = loader.get("weight");
    EXPECT_EQ(w.dtype, tinyinfer::DType::F32);
    EXPECT_EQ(w.shape, (std::vector<int64_t>{2, 3}));
    EXPECT_EQ(w.nbytes, 24u);
    EXPECT_EQ(w.numel(), 6u);
    const float* d = w.as<float>();
    for (int i = 0; i < 6; ++i) EXPECT_FLOAT_EQ(d[i], static_cast<float>(i));
}

TEST(Loader, BiasAndScalar) {
    tinyinfer::SafetensorsLoader loader;
    loader.open(kFixture);
    const float* b = loader.get("bias").as<float>();
    EXPECT_FLOAT_EQ(b[0], 0.5f);
    EXPECT_FLOAT_EQ(b[1], -1.5f);
    EXPECT_FLOAT_EQ(b[2], 2.25f);

    const auto& s = loader.get("scalar");
    EXPECT_TRUE(s.shape.empty());
    EXPECT_EQ(s.numel(), 1u);
    EXPECT_FLOAT_EQ(s.as<float>()[0], 3.14f);
}

TEST(Loader, Int32Tensor) {
    tinyinfer::SafetensorsLoader loader;
    loader.open(kFixture);
    const auto& t = loader.get("ids");
    EXPECT_EQ(t.dtype, tinyinfer::DType::I32);
    EXPECT_EQ(t.shape, (std::vector<int64_t>{4}));
    const int32_t* d = t.as<int32_t>();
    for (int i = 0; i < 4; ++i) EXPECT_EQ(d[i], i + 1);
}

TEST(Loader, MissingFileThrows) {
    tinyinfer::SafetensorsLoader loader;
    EXPECT_THROW(loader.open("/nonexistent/tiny.safetensors"), std::runtime_error);
    EXPECT_FALSE(loader.is_open());
}

TEST(Loader, MissingTensorThrows) {
    tinyinfer::SafetensorsLoader loader;
    loader.open(kFixture);
    EXPECT_THROW(loader.get("nope"), std::out_of_range);
}

TEST(Loader, TruncatedFileThrows) {
    // Write garbage and confirm the loader rejects it.
    const std::string tmp = std::string(TEST_DATA_DIR) + "/truncated.bin";
    FILE* f = fopen(tmp.c_str(), "wb");
    ASSERT_NE(f, nullptr);
    const char junk[16] = {0};
    fwrite(junk, 1, sizeof(junk), f);
    fclose(f);

    tinyinfer::SafetensorsLoader loader;
    EXPECT_THROW(loader.open(tmp), std::runtime_error);
    std::remove(tmp.c_str());
}

TEST(Loader, DtypeHelpers) {
    EXPECT_EQ(tinyinfer::dtype_size(tinyinfer::DType::F32), 4u);
    EXPECT_EQ(tinyinfer::dtype_size(tinyinfer::DType::BF16), 2u);
    EXPECT_STREQ(tinyinfer::dtype_name(tinyinfer::DType::F32), "F32");
    EXPECT_EQ(tinyinfer::dtype_from_string("BF16"), tinyinfer::DType::BF16);
    EXPECT_EQ(tinyinfer::dtype_from_string("nope"), tinyinfer::DType::UNKNOWN);
}

} // namespace
